version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fish-generate
    restart: unless-stopped
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/fish_generator
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - METAL_PRICE_API_KEY=${METAL_PRICE_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - COLLECTION_INTERVAL_WEATHER=3600s  # 1 hour
      - COLLECTION_INTERVAL_PRICE=21600s   # 6 hours
      - COLLECTION_INTERVAL_NEWS=43200s    # 12 hours
      - GENERATION_COOLDOWN=900s           # 15 minutes
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    networks:
      - fish-network

  mongodb:
    image: mongo:6
    container_name: fish-mongodb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - fish-network
    environment:
      - MONGO_INITDB_DATABASE=fish_generator
      # Uncomment these if you need authentication
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

networks:
  fish-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local 