version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fish-generate
    restart: unless-stopped
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://${MONGO_USERNAME:-fishuser}:${MONGO_PASSWORD:-yourpassword}@mongodb:27017/fish_generator?authSource=admin
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - METAL_PRICE_API_KEY=${METAL_PRICE_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - COLLECTION_INTERVAL_WEATHER=${COLLECTION_INTERVAL_WEATHER:-3600s}
      - COLLECTION_INTERVAL_PRICE=${COLLECTION_INTERVAL_PRICE:-21600s}
      - COLLECTION_INTERVAL_NEWS=${COLLECTION_INTERVAL_NEWS:-43200s}
      - GENERATION_COOLDOWN=${GENERATION_COOLDOWN:-900s}
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    networks:
      - fish-network

  mongodb:
    image: mongo:6
    container_name: fish-mongodb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - fish-network
    environment:
      - MONGO_INITDB_DATABASE=fish_generator
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-fishuser}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-yourpassword}

networks:
  fish-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local 